language: c

before_script:
  - echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get --allow-unauthenticated install sur5r-keyring
  - sudo apt-get update
  - sudo apt-get install i3

script:
  - ./autogen.sh
  - ./configure && make

compiler:
  - clang
  - gcc

branches:
  only:
    - master
    - develop
